#define OS_LINUX	1
#define ARCH_ARM	1
#define C_GCC	1
#define __32BIT__	1
#define PTHREAD_CREATE_FUNC	pthread_create
#define BUNDERSCORE	_
#define NEEDBUNDERSCORE	1
#define CORTEXA9
#define ARMV7
#define HAVE_VFP
#define HAVE_VFPV3
#define HAVE_NEON
#define L1_DATA_SIZE 32768
#define L1_DATA_LINESIZE 32
#define L2_SIZE 1048576
#define L2_LINESIZE 32
#define DTB_DEFAULT_ENTRIES 128
#define DTB_SIZE 4096
#define L2_ASSOCIATIVE 4
#define CHAR_CORENAME "CORTEXA9"
#define SLOCAL_BUFFER_SIZE	15360
#define DLOCAL_BUFFER_SIZE	7680
#define CLOCAL_BUFFER_SIZE	7680
#define ZLOCAL_BUFFER_SIZE	7680
#define GEMM_MULTITHREAD_THRESHOLD	4
